[env]
TERM = "xterm-256color"

[font]
size = 16

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"

[font.bold]
family = "MesloLGS Nerd Font"
style = "Bold"

[font.italic]
family = "MesloLGS Nerd Font"
style = "Italic"

[mouse]
hide_when_typing = true

[scrolling]
history = 100000

[selection]
save_to_clipboard = true

[window]
decorations = "none"
opacity = 0.8

[general]
import = [
	"~/.config/alacritty/catppuccin-mocha.toml",
]
