live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#434758"
blue = "#9cc4ff"
cyan = "#a3f7ff"
green = "#ddffa7"
magenta = "#e1acff"
red = "#ff8b92"
white = "#ffffff"
yellow = "#ffe585"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "#101010"
blue = "#82aaff"
cyan = "#89ddff"
green = "#c3e88d"
magenta = "#c792ea"
red = "#f07178"
white = "#d0d0d0"
yellow = "#ffcb6b"

[colors.primary]
background = "#232323"
foreground = "#eeeeff"

[colors.search.focused_match]
background = "CellForeground"
foreground = "CellBackground"

[colors.search.matches]
background = "#ffffff"
foreground = "#000000"

[font]
size = 8

[font.normal]
family = "Mononoki Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001B[15;6;5~"
key = "F5"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[>15;5~"
key = "F5"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[15;4~"
key = "F5"
mods = "Shift"

[mouse]
hide_when_typing = true

[scrolling]
history = 100000

[selection]
save_to_clipboard = true

[window]
decorations = "none"
opacity = 0.8
