import = [
	"~/.config/alacritty/themes/themes/catppuccin_mocha.toml",
]

[env]
TERM = "xterm-256color"

[font]
size = 9

[font.normal]
family = "Mononoki Nerd Font"
style = "Regular"

[mouse]
hide_when_typing = true

[scrolling]
history = 100000

[selection]
save_to_clipboard = true

[window]
decorations = "none"
opacity = 0.8
